# Generated by Django 3.0.2 on 2021-03-30 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id_buyer', models.AutoField(primary_key=True, serialize=False)),
                ('wish_room', models.IntegerField()),
                ('wish_adress', models.CharField(max_length=150)),
                ('wish_square', models.IntegerField()),
                ('budget', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id_kl', models.AutoField(primary_key=True, serialize=False)),
                ('fio', models.CharField(max_length=100)),
                ('bd', models.DateField()),
                ('phone', models.CharField(max_length=11)),
                ('mail', models.CharField(max_length=100)),
                ('pasp_seria', models.CharField(max_length=4)),
                ('pasp_nomer', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id_seller', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=10)),
                ('id_kl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Klient')),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id_fl', models.AutoField(primary_key=True, serialize=False)),
                ('coast', models.IntegerField()),
                ('descr', models.TextField()),
                ('rooms', models.IntegerField()),
                ('adress', models.CharField(max_length=150)),
                ('square_f', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('id_seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Seller')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id_contract', models.AutoField(primary_key=True, serialize=False)),
                ('time_to_sale', models.DateField()),
                ('coast', models.IntegerField()),
                ('proc_for_comp', models.IntegerField()),
                ('time_create', models.DateField(auto_now_add=True)),
                ('id_buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Buyer')),
                ('id_fl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Flat')),
                ('id_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Seller')),
            ],
        ),
        migrations.AddField(
            model_name='buyer',
            name='id_kl',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Klient'),
        ),
    ]
